import re
from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.goto("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
    page.get_by_role("textbox", name="Username").click()
    page.get_by_role("textbox", name="Username").press("CapsLock")
    page.get_by_role("textbox", name="Username").fill("A")
    page.get_by_role("textbox", name="Username").press("CapsLock")
    page.get_by_role("textbox", name="Username").fill("Admin")
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill("admin123")
    page.get_by_role("button", name="Login").click()
    page.get_by_role("link", name="PIM").click()
    page.get_by_role("button", name=" Add").click()
    page.get_by_role("textbox", name="First Name").click()
    page.get_by_role("textbox", name="First Name").press("CapsLock")
    page.get_by_role("textbox", name="First Name").fill("R")
    page.get_by_role("textbox", name="First Name").press("CapsLock")
    page.get_by_role("button", name="Save").click()
    page.get_by_text("Required", exact=True).click()
    expect(page.locator("form")).to_contain_text("Required")
    page.get_by_role("textbox", name="First Name").click()
    page.get_by_role("textbox", name="First Name").fill("Rosana")
    page.get_by_role("textbox", name="Middle Name").click()
    page.get_by_role("textbox", name="Middle Name").press("CapsLock")
    page.get_by_role("textbox", name="Middle Name").fill("A")
    page.get_by_role("textbox", name="Middle Name").press("CapsLock")
    page.get_by_role("textbox", name="Middle Name").fill("Abdelbaset")
    page.get_by_role("textbox", name="Last Name").click()
    page.get_by_role("textbox", name="Last Name").press("CapsLock")
    page.get_by_role("textbox", name="Last Name").fill("A")
    page.get_by_role("textbox", name="Last Name").press("CapsLock")
    page.get_by_role("textbox", name="Last Name").fill("Abukwaik")
    page.get_by_role("textbox").nth(4).click()
    page.get_by_role("textbox").nth(4).click()
    page.get_by_role("textbox").nth(4).fill("0422")

    page.get_by_role("button").nth(4).click()
    page.get_by_role("button", name="Choose File").set_input_files("SRS.pdf")
    expect(page.locator("form")).to_contain_text("File type not allowed")
    page.get_by_role("button").nth(4).click()
    page.get_by_role("button", name="Choose File").set_input_files("NDA for contractors.docx")
    expect(page.locator("form")).to_contain_text("Attachment Size Exceeded")

    page.get_by_role("button").nth(4).click()
    page.get_by_role("button", name="Choose File").set_input_files("WhatsApp Image 2026-03-12 at 1.05.22 PM.jpeg")
    page.get_by_role("button").nth(4).click()
    expect(page.locator("form")).to_contain_text("File type not allowed")
    page.get_by_role("button", name="Choose File").set_input_files("shorts.png")
    page.get_by_role("button", name="Save").click()
    page.goto("https://opensource-demo.orangehrmlive.com/web/index.php/pim/viewPersonalDetails/empNumber/227")
  